//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthenApply
    {
        public long AuthenId { get; set; }
        public string UsersId { get; set; }
        public string CreateType { get; set; }
        public string PriceRange { get; set; }
        public string AuthenApplyState { get; set; }
        public string Describe { get; set; }
        public string DealerId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
