//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TheCreationEntities : DbContext
    {
        public TheCreationEntities()
            : base("name=TheCreationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Applys> Applys { get; set; }
        public virtual DbSet<AuthenApply> AuthenApply { get; set; }
        public virtual DbSet<Collect> Collect { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<Creator> Creator { get; set; }
        public virtual DbSet<Evaluate> Evaluate { get; set; }
        public virtual DbSet<EveryImg> EveryImg { get; set; }
        public virtual DbSet<Focus> Focus { get; set; }
        public virtual DbSet<likeIt> likeIt { get; set; }
        public virtual DbSet<OrderApply> OrderApply { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<PersonMsg> PersonMsg { get; set; }
        public virtual DbSet<Production> Production { get; set; }
        public virtual DbSet<PublicMsg> PublicMsg { get; set; }
        public virtual DbSet<Reply> Reply { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<SysMsg> SysMsg { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersLevel> UsersLevel { get; set; }
        public virtual DbSet<UsersLogin> UsersLogin { get; set; }
        public virtual DbSet<Vote> Vote { get; set; }
        public virtual DbSet<Voted> Voted { get; set; }
        public virtual DbSet<VoteDetail> VoteDetail { get; set; }
        public virtual DbSet<All_Users_Fans_View> All_Users_Fans_View { get; set; }
        public virtual DbSet<All_Works_Comment_View> All_Works_Comment_View { get; set; }
        public virtual DbSet<All_Works_Hot_View> All_Works_Hot_View { get; set; }
        public virtual DbSet<Creator_Evaluate> Creator_Evaluate { get; set; }
        public virtual DbSet<Creator_Nmae> Creator_Nmae { get; set; }
        public virtual DbSet<Creator_Type> Creator_Type { get; set; }
        public virtual DbSet<Hot_Good_Works> Hot_Good_Works { get; set; }
        public virtual DbSet<most_comment_creator> most_comment_creator { get; set; }
        public virtual DbSet<Most_Evaluate_Creator_View> Most_Evaluate_Creator_View { get; set; }
        public virtual DbSet<Music_Works_Hot> Music_Works_Hot { get; set; }
        public virtual DbSet<newest_comment> newest_comment { get; set; }
        public virtual DbSet<newst_creator_production> newst_creator_production { get; set; }
        public virtual DbSet<P_Type> P_Type { get; set; }
        public virtual DbSet<Picture_Works_Hot> Picture_Works_Hot { get; set; }
        public virtual DbSet<Relevant_Type> Relevant_Type { get; set; }
        public virtual DbSet<Tag_Hot> Tag_Hot { get; set; }
        public virtual DbSet<Text_Works_Hot> Text_Works_Hot { get; set; }
        public virtual DbSet<Tot_Comment> Tot_Comment { get; set; }
        public virtual DbSet<Tot_Fans> Tot_Fans { get; set; }
        public virtual DbSet<tot_hot_users> tot_hot_users { get; set; }
        public virtual DbSet<Tot_Like> Tot_Like { get; set; }
        public virtual DbSet<Tot_Works> Tot_Works { get; set; }
        public virtual DbSet<UnEvaluate> UnEvaluate { get; set; }
        public virtual DbSet<Users_Level_View> Users_Level_View { get; set; }
        public virtual DbSet<Video_Works_Hot> Video_Works_Hot { get; set; }
        public virtual DbSet<RcptAddress> RcptAddress { get; set; }
        public virtual DbSet<ShopCart> ShopCart { get; set; }
        public virtual DbSet<ShopEvaluate> ShopEvaluate { get; set; }
        public virtual DbSet<ShopInfoMore> ShopInfoMore { get; set; }
        public virtual DbSet<ShopOrder> ShopOrder { get; set; }
        public virtual DbSet<ShopOrderDetail> ShopOrderDetail { get; set; }
        public virtual DbSet<ShopProduct> ShopProduct { get; set; }
        public virtual DbSet<ShopProductTag> ShopProductTag { get; set; }
        public virtual DbSet<ShopProductType> ShopProductType { get; set; }
        public virtual DbSet<SProductSubClass> SProductSubClass { get; set; }
        public virtual DbSet<Blog> Blog { get; set; }
        public virtual DbSet<BlogComment> BlogComment { get; set; }
    
        public virtual ObjectResult<All_MyFocus_Works_View_Result> All_MyFocus_Works_View(string u_ID)
        {
            var u_IDParameter = u_ID != null ?
                new ObjectParameter("U_ID", u_ID) :
                new ObjectParameter("U_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<All_MyFocus_Works_View_Result>("All_MyFocus_Works_View", u_IDParameter);
        }
    
        public virtual ObjectResult<Proc_Get_Works_Result> Proc_Get_Works(string u_ID)
        {
            var u_IDParameter = u_ID != null ?
                new ObjectParameter("U_ID", u_ID) :
                new ObjectParameter("U_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Get_Works_Result>("Proc_Get_Works", u_IDParameter);
        }
    
        public virtual int proc_init_CommentCount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_init_CommentCount");
        }
    
        public virtual int proc_init_HotCoun(Nullable<int> work_ID)
        {
            var work_IDParameter = work_ID.HasValue ?
                new ObjectParameter("Work_ID", work_ID) :
                new ObjectParameter("Work_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_init_HotCoun", work_IDParameter);
        }
    
        public virtual int proc_init_UserLevel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_init_UserLevel");
        }
    
        public virtual ObjectResult<Users_FoucusMe_View_Result> Users_FoucusMe_View(string u_ID)
        {
            var u_IDParameter = u_ID != null ?
                new ObjectParameter("U_ID", u_ID) :
                new ObjectParameter("U_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Users_FoucusMe_View_Result>("Users_FoucusMe_View", u_IDParameter);
        }
    }
}
