//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class most_comment_creator
    {
        public string UsersName { get; set; }
        public string CreateType { get; set; }
        public System.DateTime CertificationDate { get; set; }
        public string HeadUrl { get; set; }
        public string UsersId { get; set; }
        public Nullable<int> comt_count { get; set; }
    }
}
