//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderApply
    {
        public long ApplyId { get; set; }
        public string UsersId { get; set; }
        public int QOrderId { get; set; }
        public string ApplyDescrib { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public string ApplyState { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Users Users { get; set; }
    }
}
