//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicMsg
    {
        public long PublicMsgId { get; set; }
        public string SenderId { get; set; }
        public string PublicMsgContent { get; set; }
        public System.DateTime SendTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
