//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopInfoMore
    {
        public long IMID { get; set; }
        public long ProductID { get; set; }
        public string Imgurl1 { get; set; }
        public string Imgurl2 { get; set; }
        public string Imgurl3 { get; set; }
        public string Imgurl4 { get; set; }
        public string Imgurl5 { get; set; }
        public string Imgurl6 { get; set; }
        public string Imgurl7 { get; set; }
    
        public virtual ShopProduct ShopProduct { get; set; }
    }
}
