//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopEvaluate
    {
        public long EvaluateID { get; set; }
        public string UsersId { get; set; }
        public long OrderID { get; set; }
        public string Content { get; set; }
        public System.DateTime EvaDate { get; set; }
        public string EvaImg1 { get; set; }
        public string EvaImg2 { get; set; }
        public string EvaImg3 { get; set; }
        public string EvaImg4 { get; set; }
        public string EvaImg5 { get; set; }
    
        public virtual ShopOrder ShopOrder { get; set; }
        public virtual Users Users { get; set; }
    }
}
