//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SProductSubClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SProductSubClass()
        {
            this.ShopCart = new HashSet<ShopCart>();
            this.ShopOrderDetail = new HashSet<ShopOrderDetail>();
        }
    
        public long SubID { get; set; }
        public long ProductID { get; set; }
        public string PStyleDescribe { get; set; }
        public long LeftCount { get; set; }
        public string MiniImg { get; set; }
        public decimal Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopCart> ShopCart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopOrderDetail> ShopOrderDetail { get; set; }
        public virtual ShopProduct ShopProduct { get; set; }
    }
}
