//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysMsg
    {
        public long SysMsgId { get; set; }
        public string SenderId { get; set; }
        public string ReceptId { get; set; }
        public string SysMsgContent { get; set; }
        public System.DateTime SendTime { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Users Users { get; set; }
    }
}
