//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Creator()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public string CreatorId { get; set; }
        public System.DateTime CertificationDate { get; set; }
        public string CreateType { get; set; }
        public int CreatorCredit { get; set; }
        public string State { get; set; }
        public int CreatorLevel { get; set; }
        public int FinishedCount { get; set; }
        public Nullable<decimal> GoodRate { get; set; }
        public int EfctCmpltCnt { get; set; }
        public string PriceRange { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
