//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hot_Good_Works
    {
        public string UsersId { get; set; }
        public string UsersName { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
        public int UsersLevel { get; set; }
        public int Credit { get; set; }
        public string State { get; set; }
        public int OrderCount { get; set; }
        public int ChargebackCount { get; set; }
        public string Hobby { get; set; }
        public string CreatorId { get; set; }
        public string HeadUrl { get; set; }
        public Nullable<int> ProductionId { get; set; }
        public long PublisherNo { get; set; }
        public string ProductionName { get; set; }
        public string PublishDate { get; set; }
        public System.DateTime ProductionContent { get; set; }
        public string ProductionType { get; set; }
        public string ViewCount { get; set; }
        public int LikeCount { get; set; }
        public int CommentCount { get; set; }
        public int Tag1 { get; set; }
        public string Tag2 { get; set; }
        public string Tag3 { get; set; }
        public int ImgUrl1 { get; set; }
    }
}
