//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class newst_creator_production
    {
        public long ProductionId { get; set; }
        public string PublisherNo { get; set; }
        public string ProductionName { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public string ProductionContent { get; set; }
        public string ProductionType { get; set; }
        public long ViewCount { get; set; }
        public int LikeCount { get; set; }
        public int CommentCount { get; set; }
        public string Tag { get; set; }
        public string ImgUrl { get; set; }
        public int HotCount { get; set; }
        public string Describe { get; set; }
    }
}
