//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShopProduct()
        {
            this.ShopInfoMore = new HashSet<ShopInfoMore>();
            this.SProductSubClass = new HashSet<SProductSubClass>();
        }
    
        public long ProductID { get; set; }
        public string PName { get; set; }
        public int TypeID { get; set; }
        public int TagId { get; set; }
        public string Describe { get; set; }
        public string ImgUrl { get; set; }
        public decimal Price { get; set; }
        public long LeftCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopInfoMore> ShopInfoMore { get; set; }
        public virtual ShopProductTag ShopProductTag { get; set; }
        public virtual ShopProductType ShopProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SProductSubClass> SProductSubClass { get; set; }
    }
}
