//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public int LabelId { get; set; }
        public string LabelName { get; set; }
        public string LabelType { get; set; }
        public string LabelImg { get; set; }
    }
}
