//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnEvaluate
    {
        public string UsersName { get; set; }
        public int OrderId { get; set; }
        public string UsersId { get; set; }
        public string CreatorId { get; set; }
        public decimal total_amt { get; set; }
        public System.DateTime BuyDate { get; set; }
        public System.DateTime FinishDate { get; set; }
        public string OrderState { get; set; }
        public string NeedDescrib { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> ActualFinishDate { get; set; }
        public string CreatorName { get; set; }
        public string CreateType { get; set; }
    }
}
