//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voted
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voted()
        {
            this.VoteDetail = new HashSet<VoteDetail>();
        }
    
        public long VotedId { get; set; }
        public string Detail { get; set; }
        public string ImgUrl { get; set; }
        public string ReferenceId { get; set; }
        public long VoteId { get; set; }
    
        public virtual Vote Vote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VoteDetail> VoteDetail { get; set; }
    }
}
